[pytest]
testpaths = Script
pythonpath = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v -s --html=Report/report.html --self-contained-html --alluredir=Report/allure-results
